//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHoc
    {
        public string ID_BaiHoc { get; set; }
        public string TieuDe { get; set; }
        public string Nguon { get; set; }
        public string ID_KhoaHoc { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
