//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietThanhToan
    {
        public string ID_CTTT { get; set; }
        public string ID_ThanhToan { get; set; }
        public string ID_KhoaHoc { get; set; }
        public string GiaTien { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
