//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMT
    {
        public string ID_CMT { get; set; }
        public string ID_Rep { get; set; }
        public string IDUser { get; set; }
        public string noidung { get; set; }
        public Nullable<System.DateTime> ThoiGiangDang { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
