//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoaHoc()
        {
            this.BaiHocs = new HashSet<BaiHoc>();
            this.ChitietThanhToans = new HashSet<ChitietThanhToan>();
            this.NguoiDungKhoaHocs = new HashSet<NguoiDungKhoaHoc>();
        }
    
        public string ID_KhoaHoc { get; set; }
        public string Ten { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public string TomTat { get; set; }
        public string Anh { get; set; }
        public Nullable<System.DateTime> ThoiGianDangNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiHoc> BaiHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietThanhToan> ChitietThanhToans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDungKhoaHoc> NguoiDungKhoaHocs { get; set; }
    }
}
