//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhToan()
        {
            this.ChitietThanhToans = new HashSet<ChitietThanhToan>();
        }
    
        public string ID_ThanhToan { get; set; }
        public string IDUser { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietThanhToan> ChitietThanhToans { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
